version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: rese_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    environment:
      - SERVER_NAME=rese-rflm.onrender.com
    depends_on:
      - php
    networks:
      - rese_network
    restart: always

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: rese_php
    volumes:
      - ./src:/var/www/
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=sql211.infinityfree.com
      - DB_PORT=3306
      - DB_DATABASE=if0_37912852_rese_production
      - DB_USERNAME=if0_37912852
      - DB_PASSWORD=BXmbDwM2TM
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    restart: always
    networks:
      - rese_network

  mysql:
    image: mysql:8.0.26
    container_name: rese_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: if0_37912852_rese_production
      MYSQL_USER: if0_37912852
      MYSQL_PASSWORD: BXmbDwM2TM
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - rese_network
    restart: always

networks:
  rese_network:
    driver: bridge
