services:
  nginx:
    image: nginx:latest
    container_name: rese_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
      - ${SRC_DIR}:/var/www/
    depends_on:
      - php
    networks:
      - rese_network
    restart: always

  php:
    build:
      context: .
      dockerfile: ./docker/php/${DOCKERFILE}
      args:
        NGINX_CONF_FILE: ${NGINX_CONF_FILE}
        APP_ENV: ${APP_ENV}
    container_name: rese_php
    volumes:
      - ${SRC_DIR}:/var/www/
    ports:
      - "9000:9000"
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql
    restart: always
    networks:
      - rese_network

  mysql:
    image: mysql:8.0.26
    container_name: rese_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - rese_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: rese_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql
    ports:
      - 8080:80
    restart: always
    networks:
      - rese_network

  mailhog:
    image: mailhog/mailhog
    container_name: rese_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - rese_network

networks:
  rese_network:
    driver: bridge
